spring.application.name=KahveKosesi
# ===================================================================
# SERVER CONFIGURATION (Uygulaman?n çal??aca?? port)
# ===================================================================
server.port=8080

# ===================================================================
# DATABASE CONFIGURATION (H2 Veri Taban? Ayarlar?)
# ===================================================================

spring.datasource.url=jdbc:h2:mem:kahvekosesi
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 konsolunu taray?c?dan (localhost:8080/h2-console) açabilmemiz için aktif eder
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===================================================================
# JPA / HIBERNATE CONFIGURATION (SQL ve Hibernate Ayarlar?)
# ===================================================================
# Java s?n?flar?m?za göre tablolar? otomatik olu?turur (create-drop: uygulama kapan?nca tablolar temizlenir)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# THYMELEAF CONFIGURATION (Arayüz De?i?ikliklerini Anl?k Görmek ?çin)
# ===================================================================
spring.thymeleaf.cache=false